spring:
  application:
    name: catalog-service

server:
  port: ${PORT:${SERVER_PORT:0}}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

idRandom: ${random.value}
message: Mensaje desde la configuracion por DEFECTO