server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: lb://movie-service
          predicates:
            - Path=/api/v1/movies/**
        - id: catalogRoute
          uri: lb://catalog-service
          predicates:
            - Path=/api/v1/catalog/**
          filters:
            - AddRequestHeader=user-request-header, custom-user-request-header
            - AddResponseHeader=user-respons-header, custom-user-response-header
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}