spring:
  application:
    name: serie-service
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017

queue:
  message:
    serie: workingSerie

server:
  port: ${PORT:${SERVER_PORT:0}}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  traicing:
    sampling:
      probability: 1.0
  metrics:
    export:
      zipkin:
        enabled: true
        baseUrl: http://localhost:9411